# Generated by Django 5.2.8 on 2025-12-05 12:38

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('telefone', 'Telefone'), ('celular', 'Celular'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('valor', models.CharField(max_length=150)),
                ('principal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contato_empresa',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_endereco', models.CharField(default='RESIDENCIAL', max_length=50)),
                ('logradouro', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('principal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_arquivo', models.TextField()),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(max_length=100)),
                ('tamanho_arquivo', models.BigIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ativa', max_length=20)),
            ],
            options={
                'db_table': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
                ('goa', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[core.models.validate_goa])),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Relacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_origem', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
                ('tipo_destino', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
                ('tipo_relacionamento', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('participacao', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('eh_auto', models.BooleanField(default=False)),
                ('fonte_importacao', models.CharField(blank=True, max_length=100, null=True)),
                ('confiabilidade', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
            ],
            options={
                'db_table': 'relacionamento',
            },
        ),
        migrations.CreateModel(
            name='SocioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf_cnpj', models.CharField(blank=True, db_index=True, max_length=14, null=True)),
                ('nome_socio', models.CharField(max_length=300)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('participacao_percentual', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('qualificacao', models.CharField(blank=True, max_length=150, null=True)),
                ('suspeita_obito', models.BooleanField(default=False)),
                ('nome_mae', models.CharField(blank=True, max_length=300, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('ordem_exibicao', models.SmallIntegerField(default=99)),
                ('fonte_importacao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'socio_empresa',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fisica', serialize=False, to='core.pessoa')),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=300, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=300, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=200, null=True)),
                ('vinculo', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('possui_veiculos', models.BooleanField(default=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('marca_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_veiculo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cor_veiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('idade', models.SmallIntegerField(blank=True, null=True)),
                ('suspeita_obito', models.BooleanField(default=False)),
                ('qualificacao_socio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pessoa_fisica',
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='juridica', serialize=False, to='core.pessoa')),
                ('razao_social', models.CharField(max_length=300)),
                ('nome_fantasia', models.CharField(blank=True, max_length=300, null=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('situacao_cadastral', models.CharField(default='ATIVA', max_length=50)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('porte_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('cnae_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae_descricao', models.TextField(blank=True, null=True)),
                ('mei', models.BooleanField(default=False)),
                ('optante_simples', models.BooleanField(default=False)),
                ('data_opcao_simples', models.DateField(blank=True, null=True)),
                ('data_exclusao_simples', models.DateField(blank=True, null=True)),
                ('possui_filial', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pessoa_juridica',
            },
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['goa'], name='pessoa_goa_f6140e_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['tipo'], name='pessoa_tipo_72035c_idx'),
        ),
        migrations.AddField(
            model_name='foto',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='contatoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='pessoa_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_destino', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='pessoa_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_origem', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='socioempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='socioempresa',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes', to='core.pessoa'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['pessoa'], name='endereco_pessoa__cc9ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['cep'], name='endereco_cep_5d4a93_idx'),
        ),
        migrations.AddIndex(
            model_name='relacionamento',
            index=models.Index(fields=['pessoa_origem'], name='relacioname_pessoa__a52475_idx'),
        ),
        migrations.AddIndex(
            model_name='relacionamento',
            index=models.Index(fields=['pessoa_destino'], name='relacioname_pessoa__106e85_idx'),
        ),
        migrations.AddIndex(
            model_name='relacionamento',
            index=models.Index(fields=['tipo_relacionamento'], name='relacioname_tipo_re_a6f3be_idx'),
        ),
        migrations.AddIndex(
            model_name='socioempresa',
            index=models.Index(fields=['empresa'], name='socio_empre_empresa_a91dad_idx'),
        ),
        migrations.AddIndex(
            model_name='socioempresa',
            index=models.Index(fields=['cpf_cnpj'], name='socio_empre_cpf_cnp_437ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='socioempresa',
            index=models.Index(fields=['nome_socio'], name='socio_empre_nome_so_cb886d_idx'),
        ),
    ]
