# Generated by Django 5.2.8 on 2026-01-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contatoempresa_endereco_foto_pessoa_relacionamento_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pessoa',
            name='pessoa_goa_f6140e_idx',
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cidade_filial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='data_situacao_cadastral',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='endereco_filial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='situacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='situacao_simples_nacional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='telefone1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
